name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  sonarqube:
    runs-on: macOS-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1.24.0
        with:
            swift-version: 4

      - name: Build and Analyze
        run: |
          swift build
          sonar-scanner

        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_URL }}
